FROM node:18-alpine

WORKDIR /data

RUN npm install -g json-server --silent

COPY ./api /data

EXPOSE 3000

CMD ["json-server", "--watch", "/data/companies-lookup.json", "--host", "0.0.0.0", "--port", "3000"]
